# Generated by Django 6.0.5 on 2026-06-01 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('warning', 'Warning'), ('info', 'Info'), ('danger', 'Danger')], max_length=10)),
                ('mensaje', models.TextField()),
                ('area', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Alerta',
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id_capacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_fin', models.DateField(null=True)),
                ('instructor', models.CharField(max_length=100, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Capacitacion',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('cargo', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Empleado',
            },
        ),
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id_metrica', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=50, null=True)),
                ('sub', models.CharField(max_length=150, null=True)),
                ('pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('color', models.CharField(max_length=80, null=True)),
                ('text_color', models.CharField(max_length=80, null=True)),
            ],
            options={
                'db_table': 'Metrica',
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id_objetivo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('area', models.CharField(max_length=50, null=True)),
                ('estado', models.CharField(choices=[('COMPLETADO', 'Completado'), ('EN_PROGRESO', 'En progreso'), ('PENDIENTE', 'Pendiente'), ('EN_RIESGO', 'En riesgo')], default='PENDIENTE', max_length=20)),
                ('progreso', models.IntegerField(default=0)),
                ('responsable', models.CharField(max_length=100, null=True)),
                ('fecha_limite', models.DateField(null=True)),
            ],
            options={
                'db_table': 'Objetivo',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoCapacitacion',
            fields=[
                ('id_empleado_capacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asistencia', models.DateField(null=True)),
                ('estado', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('COMPLETADO', 'Completado'), ('ABANDONADO', 'Abandonado')], default='INSCRITO', max_length=20)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('id_capacitacion', models.ForeignKey(db_column='id_capacitacion', on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.capacitacion')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.empleado')),
            ],
            options={
                'db_table': 'Empleado_Capacitacion',
            },
        ),
    ]
